
target "SMRBaseCoreDemo" do
    platform:ios, '9.0'
    use_frameworks!
    
    #### SMRCoreKit.SMRNetwork
    pod 'AFNetworking', '3.2.1', :inhibit_warnings => true
    pod 'YYCache', '1.0.4', :inhibit_warnings => true
    #### SMRCoreKit.SMRDataBase
    pod 'FMDB', '2.7.2', :inhibit_warnings => true
    #### SMRCoreKit.SMRDataBase/SMRModel
    pod 'YYModel', '1.0.4', :inhibit_warnings => true
    #### SMRCoreKit.SMRDebug
    pod 'FLEX', '2.4.0', :inhibit_warnings => true
    
    #### SMRUIKit.SMRNavigationView
    pod 'PureLayout', '3.1.4', :inhibit_warnings => true
    pod 'SDWebImage', '4.4.3', :inhibit_warnings => true
    #### SMRUIKit.SMRController
    pod 'MJRefresh', '3.1.15.7', :inhibit_warnings => true
    pod 'IQKeyboardManager', '~> 3.3.7', :inhibit_warnings => true
    #### SMRUIKit.SMRLBXScanController
    pod 'LBXScan', '2.3', :inhibit_warnings => true
    
    #### SMRUtilsKit.SMRUtils
    pod 'YYText', '1.0.7', :inhibit_warnings => true
    pod 'MBProgressHUD', '1.1.0', :inhibit_warnings => true
    
    ####
    pod 'CocoaSecurity', '1.2.4', :inhibit_warnings => true
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO' if config.build_settings['SDKROOT'] == 'iphoneos'
        end
    end
end
