DebugBranchReleaseMode,DebugBranchDebugMode = 'releasemode','debugmode'
DebugBranch = DebugBranchDebugMode

target "SMRBaseCoreDemo" do
    platform:ios, '9.0'
    use_frameworks!
    
    pod 'SMRDebug', :git => 'git@github.com:sghick/framework-SMRDebug.git', :commit => DebugBranch
    
    #### SMRCoreKit.SMRNetwork
    pod 'AFNetworking', '4.0.1', :inhibit_warnings => true
    pod 'YYCache', '1.0.4', :inhibit_warnings => true
    #### SMRCoreKit.SMRDataBase
    pod 'FMDB', '2.7.2', :inhibit_warnings => true
    #### SMRCoreKit.SMRDataBase/SMRModel
    pod 'YYModel', '1.0.4', :inhibit_warnings => true
    #### SMRCoreKit.SMRDebug
    pod 'FLEX', :inhibit_warnings => true
    
    #### SMRUIKit.SMRNavigationView
    pod 'PureLayout', '3.1.4', :inhibit_warnings => true
    pod 'SDWebImage', '5.7.0', :inhibit_warnings => true
    #### SMRUIKit.SMRController
    pod 'MJRefresh', '3.1.15.7', :inhibit_warnings => true
    pod 'IQKeyboardManager', '~> 3.3.7', :inhibit_warnings => true
    
    #### SMRUtilsKit.SMRUtils
    pod 'YYText', '1.0.7', :inhibit_warnings => true
    pod 'MBProgressHUD', '1.1.0', :inhibit_warnings => true
    
    ####
    pod 'CocoaSecurity', '1.2.4', :inhibit_warnings => true
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO' if config.build_settings['SDKROOT'] == 'iphoneos'
        end
    end
end
